### ISSUE TITLE
No default size in FontIcon class

### ISSUE THREAD

**Issue by AlexFalappa** [aalmiray/ikonli#14]
Forgetting to set the icon size as in:
``` java
FontIcon fi = new FontIcon();
fi.setIkon(FontAwesome.AMBULANCE);
jLabel.setIcon(fi);
```
leads to:
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
	at org.kordamp.ikonli.swing.FontIcon.paintIcon(FontIcon.java:51)
	at sun.swing.plaf.synth.SynthIcon.paintIcon(SynthIcon.java:67)
...
```
This is because the `height` and `width` members in `FontIcon` are left uninitialized, they could be set as the default `iconSize` (16)

**Comment by AlexFalappa** [comment]
Alternatively the `height` and `weight` values could be recalculated lazily
