### ISSUE TITLE
Icon description 'fas-globe' is invalid!

### ISSUE THREAD

**Issue by pupeno** [aalmiray/ikonli#17]
I'm updating from font-awesome to font-awesome5 and I'm getting this error:

```
Caused by: java.lang.IllegalArgumentException: Icon description 'fas-globe' is invalid!
	at org.kordamp.ikonli.fontawesome5.FontAwesomeRegular.findByDescription(FontAwesomeRegular.java:146)
	at org.kordamp.ikonli.fontawesome5.FontAwesomeSolidIkonHandler.resolve(FontAwesomeSolidIkonHandler.java:35)
	at org.kordamp.ikonli.javafx.FontIcon.setIconLiteral(FontIcon.java:252)
```

The code that tries to use it looks like this:

```
<Tab closable="false" text="Web Sites">
    <graphic>
        <FontIcon iconLiteral="fas-globe"/>
    </graphic>
```

I can see `fas-globe` defined on `FontAwesomeSolid` but not `FontAwesomeRegular`. I'm not sure why ` FontAwesomeRegular` is being used.

**Comment by pupeno** [comment]
I think the problem is in this line:

https://github.com/aalmiray/ikonli/blob/master/subprojects/ikonli-fontawesome5-pack/src/main/java/org/kordamp/ikonli/fontawesome5/FontAwesomeSolidIkonHandler.java#L35

I think it should using `FontAwesomeSolid` instead.

**Comment by pupeno** [comment]
Thanks for merging these pull requests. Do you know when you'll release these fixes?

**Comment by aalmiray** [comment]
New release `2.1.1` available just now. Thank you for the updates! 😄
