### ISSUE TITLE
NPE when printing a FontIcon instance created used no-args constructor

### ISSUE THREAD

**Issue by aalmiray** [aalmiray/ikonli#40]
Caused by: java.lang.NullPointerException
            at org.kordamp.ikonli.javafx/org.kordamp.ikonli.javafx.FontIcon.toString(FontIcon.java:112)
            at java.base/java.lang.String.valueOf(String.java:2951)
            at java.base/java.io.PrintStream.println(PrintStream.java:897)
            at org.kordamp.ikonli.sampler.javafx/org.kordamp.ikonli.sampler.javafx.Sampler.start(Sampler.java:82)
            at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
            at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
            at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
            at java.base/java.security.AccessController.doPrivileged(Native Method)
            at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
            at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)

**Comment by aalmiray** [comment]
Reported by @jperedadnr
